name: client-daemon
version: 1
summary: A client daemon example written in Go
description: A client daemon example written in Go
confinement: strict

apps:
    daemon:
        command: daemon
        daemon: simple
    client:
        command: client

parts:
    client-daemon:
        build-packages: [ golang-go ]
        plugin: make
        source: .
